version: '{build}'

shallow_clone: true

os:
  - Windows Server 2012

platform:
  - x64

environment:
  global:
    NODE_VERSION: 5.0

cache:
  - node_modules -> package.json

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:NODE_VERSION

test_script:
  - node --version && npm --version
  - build.bat

build: off
